name: CI
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - uses: actions/checkout@master
      - name: Install packages
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@brockmdavis'
          token: '${{secrets.CI_CD_PAT}}'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.CI_CD_PAT}}
      - name: Generate Build
        run: npm run build
      - uses: brockmdavis/brockmdavis-s3-sync@master
        env:
          SOURCE_DIR: ${{ github.workspace }}
          DIST_DIR: ${{ github.workspace }}/react-app/dist/
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
